### ISSUE TITLE
I can't login to lemmy terminal viewer with my email addresss - [./ltv login "Login Failed"]

### ISSUE THREAD

**Issue by secretnamebasis** [LunaticHacker/lemmy-terminal-viewer#8] opened 2021-10-30 01:06 UTC
When I used my email address, it failed.

```
secret@secret:~$ ./ltv login
Enter your instance: lemmy.ml
Enter your username or email: secretnamebasis@keemail.me
Enter your password: 
Error: Custom { kind: Other, error: "Login Failed" }
```

When I used my username, it succeeded

```
secret@secret:~$ ./ltv login
Enter your instance: lemmy.ml
Enter your username or email: secretnamebasis
Enter your password: 
Login successful
```

**Comment by LunaticHacker** [comment] 2021-10-30 05:34
can't reproduce this, can you make sure that the email is correct?

**Comment by secretnamebasis** [comment] 2021-10-30 14:04
I updated the name to better reflect the issue. 

My email is correct. See screenshot:

![image](https://user-images.githubusercontent.com/86203717/139536032-53c66913-88f4-47db-b907-b0f0baf79df4.png)

**Comment by LunaticHacker** [comment] 2021-10-30 15:03
you must have made a typo when signing up at lemmy.ml i was able to register [a new user](https://lemmy.ml/u/notsecretnamebasis) with the email you are using. i removed the email from the account i created. you should able to fix the typo from settings in lemmy.ml. closing this because this is not a ltv issue. but feel free to ask any additional questions

**Closed by LunaticHacker** 2021-10-30 15:03 UTC
